### ISSUE TITLE
SC on Internet Archive sucks

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#200]
Basically none of the texts seem to be there, instead:

    Page cannot be displayed due to robots.txt.

It seems to be a redirect issue, it goes to this URL: https://www.suttacentral.net/robots.txt, which has: 

    User-agent: *
    Disallow: /

While https://suttacentral.net/robots.txt has:

    User-agent: *
    Allow: /

In addition, the whole interface is crapped up.

We should ensure that our site is accurately scraped. If fixing the robots issue doesn't do it, we should find out what it takes.

**Comment by ghost** [comment]
I had a question from Ven. Anandajoti a few days ago why the link to SuttaCentral on his website was not working. It was also because he had the www in the URL. Can we please make sure that if people type www.suttacentral.net it is redirected.

**Comment by blake-sc** [comment]
I just noticed that the Cloudflare subscription wasn't paid and it has lapsed to free website, that has disabled most of the custom page rules including most the redirects.

**Comment by blake-sc** [comment]
Anyway I setup nginx to do the redirect from www to non-www so this issue should be resolved now

**Comment by ghost** [comment]
Ta!

**Comment by sujato** [comment]
Does that mean the internet Archive issue is resolved? I just checked the archives at a bunch of dates. Most of them are completely crapped out, but occasionally we do get the content. But we clearly need to be much more consistently crawlable.

Also, what's up with Cloudflare? Shouldn't we get a notification from them? I notice that I don't get anything.

**Comment by blake-sc** [comment]
It should be resolved now, as any request to www.suttacentral.net will be redirected to suttacentral.net, and it should now see the corect robots.txt

**Comment by sujato** [comment]
This issue is still not resolved. In fact, since mid-Nov we have not been crawled at all. It seems that something is blocking us entirely.

https://web.archive.org/save/https://suttacentral.net/

>Bummer.
>This url is not available on the live web or can not be archived.

**Comment by blake-sc** [comment]
It's no longer saying that suttacentral is blocked, and when I use an incognito window the save page function is working so it is able to generate snapshots of pages. It still doesn't seem to have done a crawl in the past month, altough looking back through the history it doesn't seem unusual for it to not crawl the site for a month or two.

By the way I haven't changed anything it just spontaneously started working: so it's probably just archive.org being buggy/eccentric.

**Comment by sujato** [comment]
Okay, well let's keep an eye on it and see how it goes.

**Comment by sujato** [comment]
I just checked, and we got crawled on Feb 16. It seems fine! The front page is a bit mangled, but the texts and division pages seem to be there. I'll close this issue, but we should remember to check again when the new version is live.
